CREATE DATABASE IF NOT EXISTS site_vente;
USE site_vente;

CREATE TABLE IF NOT EXISTS produits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    description TEXT,
    prix DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255),
    date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP
);

